# Generated by Django 4.2.7 on 2023-12-02 01:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(default='4.0', max_length=4)),
                ('subjectArea', models.CharField(max_length=15)),
                ('rating', models.FloatField(null=True)),
                ('gradeDistributions', models.CharField(max_length=12, null=True, validators=[django.core.validators.int_list_validator])),
                ('hotseatGraph', models.CharField(blank=True, max_length=100, null=True)),
                ('classId', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Dars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussionId', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.CharField(max_length=50)),
                ('professors', models.CharField(max_length=200)),
                ('classObj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='GREG.classobj')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.CharField(max_length=20)),
                ('className', models.CharField(max_length=100)),
                ('units', models.CharField(default='4.0', max_length=4)),
                ('subjectArea', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='GREG.dars')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=20)),
                ('hours', models.CharField(max_length=20)),
                ('discussionTime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussionTimes', to='GREG.discussionsection')),
                ('lectureTime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='times', to='GREG.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='SubRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('units', models.IntegerField()),
                ('count', models.IntegerField()),
                ('classes', models.CharField(blank=True, default='', max_length=200)),
                ('subrequirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrequirements', to='GREG.requirement')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(null=True)),
                ('name', models.CharField(max_length=90)),
                ('dars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='GREG.dars')),
            ],
        ),
        migrations.AddField(
            model_name='discussionsection',
            name='lectures',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='GREG.lecture'),
        ),
        migrations.AddField(
            model_name='classobj',
            name='dars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='GREG.dars'),
        ),
    ]
