# Generated by Django 4.2.7 on 2023-12-01 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GREG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussionsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussionId', models.CharField(default='0', max_length=20)),
                ('lectures', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='GREG.lecture')),
            ],
        ),
    ]
