# Generated by Django 4.2.7 on 2023-12-01 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GREG', '0003_time_discussiontime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='discussionTime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussionTimes', to='GREG.discussionsection'),
        ),
    ]
