# Generated by Django 4.2.7 on 2023-12-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREG', '0004_alter_time_discussiontime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dars', models.FileField(upload_to='store/dars/')),
            ],
        ),
    ]
