# Generated by Django 4.2.7 on 2023-12-01 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GREG', '0005_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classId', models.CharField(max_length=20)),
                ('className', models.CharField(max_length=100)),
                ('units', models.CharField(default='4.0', max_length=4)),
                ('subjectArea', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('units', models.IntegerField()),
                ('count', models.IntegerField()),
                ('subrequirements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrequirements', to='GREG.requirement')),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.AddField(
            model_name='lecture',
            name='regClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturesR', to='GREG.registrardata'),
        ),
    ]
