# Generated by Django 4.2.7 on 2023-12-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GREG', '0006_registrardata_requirement_subrequirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subrequirement',
            name='classes',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
