# Generated by Django 4.2.7 on 2023-12-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GREG', '0007_subrequirement_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='regClass',
        ),
    ]
