# Generated by Django 4.2.7 on 2023-12-01 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GREG', '0008_remove_lecture_regclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='classobj',
            name='dars',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='GREG.dars'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='dars',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='GREG.dars'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirement',
            name='dars',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='requirments', to='GREG.dars'),
            preserve_default=False,
        ),
    ]
